### PR TITLE
Added idea of 2FA view

### PR DESCRIPTION
**Pull request by williamollio**

### CODE REVIEW

**Comment by williamollio** [comment]
I hope I didn't break anything ! Maybe it could be worth having a short look together next week or so

**Comment by williamollio** [comment]
again, I hope I didn't break anything

**Comment by williamollio** [comment]
As discussed, there is an edge when the name from the intra of the user will already exists in our DB. But we can merge it already and create another branch for that.

**Review by mhahnFr — APPROVED** [review]
All that work that has been done looks absolutely beautiful ;)

**Comment by williamollio** [comment]
@mhahnFr for some reason, the app nest doesn't start when launched inside the container but locally it does. I am on that but any input would be appreciated

**Pull request merged**
